data:
  dir_raw:
    local: ../data/raw/
    kaggle: /kaggle/input/rsna-breast-cancer-detection/
  dir_processed:
    local: ../data/processed/
    kaggle: /kaggle/input/rsna-mammography-images-as-pngs/images_as_pngs/
  train_dataframe: train.csv
  test_dataframe: test.csv
  train_images_dir: train_images/
  test_images_dir: test_images/
  dir_models: ../models/
  path_submission: ../data/output/submission.csv

hyperparams:
  train_size: 0.8
  batch_size: 32
  epochs: 2
  optimizer: adam
  loss: binary_crossentropy
  model: EfficientNet
