data:
  dir_raw:
    local: ../data/raw/
    kaggle: /kaggle/input/rsna-breast-cancer-detection/
  dir_processed:
    local:
      train: ../data/processed/
      test: ../data/processed/
    kaggle:
      train: /kaggle/input/rsna-mammography-images-as-pngs/images_as_pngs/
      test: processed/
  train_dataframe: train.csv
  test_dataframe: test.csv
  train_images_dir:
    local: train_images/
    kaggle: train_images_processed/
  test_images_dir: test_images/
  dir_models:
    local: ../models/
    kaggle: /kaggle/working/models/
  path_submission:
    local: ../data/output/submission.csv
    kaggle: /kaggle/working/models/submission.csv

hyperparams:
  train_size: 0.8
  batch_size: 16
  epochs: 1
  optimizer: adam
  loss: binary_crossentropy
  model: EfficientNet
