data:
  train_dataframe: /kaggle/input/rsna-breast-cancer-detection/train.csv
  test_frame: /kaggle/input/rsna-breast-cancer-detection/test.csv
  train_images_processed_dir: /kaggle/input/rsna-mammography-images-as-pngs/images_as_pngs/train_images_processed/
  path_model: /models/

hyperparams:
  train_size: 0.8
  batch_size: 16
  epochs: 10
  optimizer: adam
  loss: binary_crossentropy
  model: EfficientNet