data:
  base_dir: ../../data
  train_dataframe: /raw/train.csv
  test_frame: /raw/test.csv
  train_images_processed_dir: /processed/train_images_processed/
  test_images_processed_dir: /processed/test_images_processed/
  path_model: ../../models/

hyperparams:
  train_size: 0.8
  batch_size: 32
  learning_rate: 0.001
  epochs: 2
