data:
  train_dataframe: ../data/raw/train.csv
  test_frame: ../data/raw/test.csv
  train_images_processed_dir: ../data/processed/train_images_processed/
  test_images_processed_dir: ../data/processed/test_images_processed/
  path_model: ../models/

hyperparams:
  train_size: 0.8
  batch_size: 32
  epochs: 2
  optimizer: adam
  loss: binary_crossentropy
  model: EfficientNet
